#!/bin/sh

set -e 

SRC_HOME=$(pwd)/$(dirname $0)
USER_HOME="$HOME"

for arg in "$@"; do
    case ${arg} in
        --src=* ) SRC_HOME=${arg/--src=/} ;;
        --home=* ) USER_HOME=${arg/--home=/} ;;
    esac
done

echo "HOME: $USER_HOME"
echo "SRC: $SRC_HOME"
echo "FILE: $0"


mkdir -p "$USER_HOME/.local/share/bash"
mkdir -p "$USER_HOME/.config/bash"

cp -i "$SRC_HOME/.gitconfig" "$USER_HOME/"
cp -i "$SRC_HOME/.gitignore" "$USER_HOME/"
cp -i "$SRC_HOME/.vimrc"     "$USER_HOME/"

cp -i  "$SRC_HOME/src/dircolors" "$USER_HOME/.config/bash/" 